Workspaces UI
Teradata/ai-unlimited pull request #38
Opened 2024-08-19 16:06 UTC by cloud-work535

Adding new ui image to the AWS templates. ALB templates are not supported and I have to rollback the ALB template changes. ALB templates will be removed in another PR before the release date.

2024-08-22 15:46 UTC, cloud-work535 commented
**all-in-one-without-lb:**

<img width="480" alt="image" src="https://github.com/user-attachments/assets/e508f54b-bca5-47fe-98d3-ce4204a07fe1">

**ai-unlimited-without-lb**

<img width="468" alt="image" src="https://github.com/user-attachments/assets/af17b4c6-1d26-4a26-b9e3-e27013542dad">

**all-in-one-nlb**

<img width="468" alt="image" src="https://github.com/user-attachments/assets/4b482cb9-23eb-4624-bc7b-af3392f6f963">

**ai-unilimited-with-nlb**

<img width="468" alt="image" src="https://github.com/user-attachments/assets/eb043efa-fcaa-4a3f-bfe2-41a2be0173b4">

2024-08-23 14:43 UTC, RisokHdz approved these changes

2024-08-23 15:52 UTC, alicia-td approved these changes

2024-08-23 16:15 UTC, RisokHdz approved these changes

2024-08-23 18:41 UTC, johandry commented
The variable `AiUnlimitedHttpPort` should be named `AiUnlimitedAuthPort` because this is not more for HTTP.
If you do the change, make sure to rename it everywhere.

2024-08-23 19:05 UTC, johandry requested changes
There are basically these changes:
- Use `AI Unlimited UI` instead of `Workspaces UI` for the services name and description
- Use the port variables for HTTP (to be renamed) and gRPC instead of hardcoded values
- Use the UI Healthcheck URL, although there is a typo that will be fixed
- Rename the HTTP Port variable name and description to Auth Port

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-with-nlb.yaml
> +            /usr/lib/systemd/system/workspaces-ui.service:
should be `ai-unlimited-ui.service` instead `workspaces-ui.service`

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-with-nlb.yaml
> +                Description=workspaces-ui
Should be `AI Unlimited UI` instead of `workspaces-ui`

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-with-nlb.yaml
> +                  -e TD_VCD_AUTH_PORT=3000 \
If the HTTP and gRPC Port are a variables, these ports should be too.
```
-e TD_VCD_AUTH_PORT=${ AiUnlimitedHttpPort } \
-e TD_VCD_API_PORT=${ AiUnlimitedGrpcPort }  \
```

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-with-nlb.yaml
> +              workspaces-ui:
Same here, should be `ai-unlimited-ui` instead of `workspaces-ui`

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-with-nlb.yaml
> +      - !Sub "http://${ LoadBalancer.DNSName }:${ AiUnlimitedUiPort }/landing"
The UI have a health check too. Use `"http://${ LoadBalancer.DNSName }:${ AiUnlimitedUiPort }/healtcheck`.

There is a typo, that I will change in a PR this week, should be `/healthcheck` 😄

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-without-lb.yaml
> +        configure_workspaces_ui_service:
Same here `ai_unlimited_ui_service`

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-without-lb.yaml
> +            /usr/lib/systemd/system/workspaces-ui.service:
Same here `ai-unlimited-ui.service`

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-without-lb.yaml
> +                Description=workspaces-ui
Same here `AI Unlimited UI`

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-without-lb.yaml
> +              workspaces-ui:
Same here `ai-unlimited-ui`

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-without-lb.yaml
> +        start_workspaces_ui_service:
Same here `ai_unlimited_ui_service`

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-without-lb.yaml
> +                  -e TD_VCD_API_PORT=3282 \
Same comment regarding the ports, should use the variables.

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-without-lb.yaml
> +                 !Sub "http://${AiUnlimitedServer.PublicDnsName}:${AiUnlimitedUiPort}/landing",
Same comment regarding the UI healthcheck

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/ai-unlimited/ai-unlimited-without-lb.yaml
> +      - !Sub "http://${AiUnlimitedServer.PrivateDnsName}:${AiUnlimitedUiPort}/landing"
Same comment regarding the UI healthcheck

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/all-in-one/all-in-one-with-nlb.yaml
> +            - configure_workspaces_ui_service
same comment about using UI Unlimited instead of Workspaces

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/all-in-one/all-in-one-with-nlb.yaml
> +            - start_workspaces_ui_service
same comment about using UI Unlimited instead of Workspaces

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/all-in-one/all-in-one-with-nlb.yaml
> +        configure_workspaces_ui_service:
same comment about using UI Unlimited instead of Workspaces

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/all-in-one/all-in-one-with-nlb.yaml
> +            /usr/lib/systemd/system/workspaces-ui.service:
same comment about using UI Unlimited instead of Workspaces

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/all-in-one/all-in-one-with-nlb.yaml
> +                Description=workspaces-ui
same comment about using UI Unlimited instead of Workspaces

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/all-in-one/all-in-one-with-nlb.yaml
> +        start_workspaces_ui_service:
same comment about using UI Unlimited instead of Workspaces

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/all-in-one/all-in-one-with-nlb.yaml
> +              workspaces-ui:
same comment about using UI Unlimited instead of Workspaces

2024-08-23 19:05 UTC, johandry commented on deployments/aws/templates/all-in-one/all-in-one-with-nlb.yaml
> +      - !Sub "http://${ LoadBalancer.DNSName }:${ AiUnlimitedUiPort }/landing"
same comment about using the UI Healthcheck

2024-08-23 19:58 UTC, cloud-work535 commented on deployments/aws/templates/ai-unlimited/ai-unlimited-with-nlb.yaml
> +            /usr/lib/systemd/system/workspaces-ui.service:
Yes, I was changing the ui name from "workspaces-ui" to "ai-unlimited-ui" and version on my next commit. waiting for the image to be ready and UI fix to test and push them all at once.

2024-08-26 19:17 UTC, johandry requested changes

2024-08-26 19:17 UTC, johandry commented on deployments/aws/templates/all-in-one/all-in-one-with-nlb.yaml
> +                  -e TD_VCD_AUTH_PORT=3000 \
API and Auth port hardcoded, should use the variables.

2024-08-26 19:52 UTC, merged