Add workspaces UI to templates
Teradata/ai-unlimited pull request #41
Opened 2024-08-19 23:13 UTC by aopanis

## Description
Add new workspaces ui to azure deployment templates. Additionally reworked the unit files to use `-` prefix instead of `|| true` pattern (`-` prefix is the unit file way of specifying acceptable errors), and reformatted the cloud-init section. Rebased on Jack's changes and changed the version to specific versions.

## Testing
Testing was done by deploying all the templates on azure.

### all-in-one-without-lb
![Screenshot 2024-08-16 at 12 11 53 PM](https://github.com/user-attachments/assets/5040d05a-2948-4393-847b-4475923c092f)
### all-in-one-nlb
![Screenshot 2024-08-16 at 12 08 28 PM](https://github.com/user-attachments/assets/ed578ab7-7edd-4387-b8ec-5c51ef497bdc)
### ai-unlimited-without-lb
![Screenshot 2024-08-16 at 12 03 43 PM](https://github.com/user-attachments/assets/6b4b678f-73e0-4376-8637-7940f8387061)
### ai-unlimited-nlb
![Screenshot 2024-08-16 at 12 02 18 PM](https://github.com/user-attachments/assets/c9963cfd-dc3d-45d5-9407-b556ca2e8b1b)

2024-08-19 23:24 UTC, RisokHdz approved these changes, later dismissed

2024-08-23 16:12 UTC, alicia-td approved these changes, later dismissed

2024-08-23 16:15 UTC, cloud-work535 submitted a review, later dismissed

2024-08-23 19:08 UTC, johandry requested changes
The variable `AiUnlimitedHttpPort` should be renamed to `AiUnlimitedAuthPort` also the description to `port to access the AI Unlimited authentication service`. This port is not anymore for the HTTP or UI, it is for the Authentication Service

2024-08-23 19:13 UTC, johandry commented
If you have or need a health check for the UI, you can use "http://<UI URL>/healtcheck"

There is a typo, that I will change in a PR this week, should be `/healthcheck` 😄

2024-08-26 19:09 UTC, johandry approved these changes

2024-10-30 18:32 UTC, merged